### ISSUE TITLE
from geometry_utils import load_obj, export_obj

### ISSUE THREAD

**Issue by HanHan55** [daerduoCarey/where2act#4]
Hi!Great work on the Where2Act research work. I am quite inspired by your work. 

Could you help me solve the problems I have in operation?

1.when I run 'bash scripts/run_gen_offline_data.sh' in the terminal, I just generated one file 'log.txt' and It contains only two lines.am i right?

![image](https://user-images.githubusercontent.com/59916865/116055457-4ca06600-a6af-11eb-946a-9075b4b5835c.png)

2.when I run 'bash scripts/run_train_3d_critic.sh' in the terminal, It can't find the 'load_obj'.

![image](https://user-images.githubusercontent.com/59916865/116054327-229a7400-a6ae-11eb-9310-6a599946d20c.png)

Thanks.

**Comment by daerduoCarey** [comment]
1) it doesn't seem correct. Can you run "python collect_data.py 100129 Box 0 pushing" ok? It is ok that an interaction trial may fail, but in the log file, you should see the reason. I'm guessing maybe you can remove ` > /dev/null 2>&1` in https://github.com/daerduoCarey/where2act/blob/main/code/datagen.py#L56 so that you can see more debugging messages outputted to the console.

2) thanks for helping me figure out this. I've updated the code to remove dependency on `geometry_utils`.

**Comment by HanHan55** [comment]
Thanks for helping me.

1.run "python collect_data.py 100129 Box 0 pushing",It is ok that an
interaction trial failed.

[image: image.png][image: image.png]

2.I found that some data have 7 files( viz_target_pose.png ,
interaction_mask.png,  gt_nor.png, cam_XYZA.h5,  result.json, log.txt,
rgb.png), some data just have 1 file (log.txt).
I am not sure how to do right, Do all the data have 7 files?
[image: image.png][image: image.png][image: image.png]

3.I created 'data_tuple_list.txt', am I right here?
[image: image.png]

4.How long does the two networks training take?

Thanks.



Kaichun Mo ***@***.***> 于2021年4月26日周一 下午10:22写道：

**Comment by HanHan55** [comment]
Hi!

I also want to know that how long does it take to generate offline training
data.

Thanks.

汤雨涵 ***@***.***> 于2021年4月27日周二 上午9:22写道：

**Comment by HanHan55** [comment]
Hi!

I failed to intsall Rendershape. if I want to change 'Rendershape' to
'blender' for visualization ,what should I do here?
https://github.com/daerduoCarey/where2act/blob/6141c767bcd729a8404c4d6a4198dab70a0c08ce/code/utils.py#L113

Thanks!

汤雨涵 ***@***.***> 于2021年4月27日周二 下午4:30写道：

**Comment by HanHan55** [comment]
Thanks for helping me.

**1.run "python collect_data.py 100129 Box 0 pushing",It is ok that an interaction trial failed.**
![image](https://user-images.githubusercontent.com/59916865/116332097-aca82100-a803-11eb-9a66-825ffb3d3632.png)
![image](https://user-images.githubusercontent.com/59916865/116332114-b3369880-a803-11eb-9900-9326bd32c7d9.png)

**2.I found that some data have 7 files( viz_target_pose.png , interaction_mask.png,  gt_nor.png, cam_XYZA.h5,  result.json, log.txt, rgb.png), some data just have 1 file (log.txt).
I am not sure how to do right, Do all the data have 7 files?**
![image](https://user-images.githubusercontent.com/59916865/116332135-be89c400-a803-11eb-83d7-09650f03dd12.png)
![image](https://user-images.githubusercontent.com/59916865/116332142-c184b480-a803-11eb-9acc-3a20c482ec55.png)
![image](https://user-images.githubusercontent.com/59916865/116332145-c34e7800-a803-11eb-9b68-8f842689898d.png)

**3.I created 'data_tuple_list.txt', am I right here?**
![image](https://user-images.githubusercontent.com/59916865/116332150-c6496880-a803-11eb-8199-bf8d472f3ee0.png)

**4.How long does the two networks training take?how long does it take to generate offline training data.**

**5.I failed to intsall Rendershape. if I want to change 'Rendershape' to 'blender' for visualization ,what should I do here?**
https://github.com/daerduoCarey/where2act/blob/6141c767bcd729a8404c4d6a4198dab70a0c08ce/code/utils.py#L113


Thanks.

**Comment by daerduoCarey** [comment]
1/2. there could be three outcomes of an interaction trial: successful, failed, not-used. For some interaction trials, due to various reasons (e.g. the object is not stable, the part cannot stay still before the interaction), it is classified as "not-used", so these data will not be used for training (so just one log.txt is output with no data files generated). For most cases, the interaction trials are ok to use, then data files will be generated with result.json stores the two outcomes "successful" or "failed".
3. yes, `data_tuple_list.txt` lists all data names, like what you did. Notice that the data file list should only contain "successful" or "failed" trials (i.e. no "not-used" files with only a single log.txt file generated)
4. it may take a long while to generate offline data (check the table in the README for the accurate number of data I used in the paper). So you need multiple CPUs/machines to parallelize your data generation process. It roughly takes 1-3 days with 100-500 CPUs. The training of networks is fast if you only use offline generated data, say 1-2 days on decent GPU. But if you also want to generate online data to augment the training, then the data generation part is back as the main bottleneck. Again, try to get more CPU workers on data generation.
5. Yes, you can use other render scripts to render the visualization. Whatever you like. This is not part of Where2Act. This is just for visualizing the results. You can of course use MatplotLib or Blender, or even output the obj files and use MeshLab to visualize.

**Comment by HanHan55** [comment]
Hi,
Thank you for your patient answers before. I still have some questions about the training of networks.
What are the detail settings of the pretrained checkpoints?are you only use offline generated data for training networks?
And what about the model version 'model_all_final',I can't find this version.
I cant find 'finalexp-model_critic_v1_bce-pushing-None-train_critic_v1_bce_Roff/ckpts/90-network.pth ' in the folder 'final_logs'.

**Comment by daerduoCarey** [comment]
no there are online data as well. 

You don't need to worry about the `model_all_final` model-version. This is for the pretrained ckpt only. You should be able to train your models using the released model files.

why and where do you need this 'finalexp-model_critic_v1_bce-pushing-None-train_critic_v1_bce_Roff`? this is again a legacy training log. I've cleaned up the code a bit for release, so you no longer will see it in your training.
